## Generaly we do not need to set the package_name it will be take from files name but 
## in case there is a hash in file name, we need to set the package_name and remove any other old packages from input folder.
#package_name : banana
#replacement_regex_txt : []
replacement_regex_spdx : [ "^Creator: Person: .*()$" = "Creator: Person: XXXX"]
