#Please move the Readme file inside input folder and paste the right name of the file
file_path : oss/input/ReadMe_OSS_jquery-ui-1.12.1.zip_1709826063.txt
#package_name : banana
replacement_regex_texts : ["MAIN LICENSES" = "LICENSES"]