#Please move the Readme file inside input folder and paste the right name of the file
file_path : oss/input/ReadMe_OSS_XXXX.txt
#package_name : banana
replacement_regex_texts : ["MAIN LICENSES" = "LICENSES"]