file_path : PUT_Your_PATH/SPDX2TV_jquery-ui-1.12.1.zip_1709819064.spdx
#removal_file_ending : .zip_1709819064.spdx
destination_path : PUT_Your_PATH/
replacement_regex_texts : [ "^Creator: Person: .*()$" = "Creator: Person: Parian Golchin", "^PackageLicenseConcluded: .*\n$" = "PackageLicenseConcluded: NOASSERTION\n"]