# SPDX-FileCopyrightText: Maximilian Huber <maximilian.huber@tngtech.com>
# SPDX-FileCopyrightText: Helio Chissini de Castro <heliocastro@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: spdx/tools-java workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  syntax-check-of-tag-value:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "bootstrap spdx/tools-java"
        run: .github/workflows/scripts/spdx-tools-java-wrapper.sh bootstrap

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.spdx

      - name: "verify changed tag-value documents"
        run: .github/workflows/scripts/spdx-tools-java-wrapper.sh verify_many ${{ steps.changed-files.outputs.all_changed_files }}
        if: github.event_name == 'pull_request'

      - name: "verify all tag-value documents"
        run: .github/workflows/scripts/spdx-tools-java-wrapper.sh verify
        if: github.event_name != 'pull_request'
